version: '3.8'
services:
  ivr_stand:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    restart: always
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=test
    depends_on:
      - db

    networks:
      - ivr_network
    devices:
      - /dev/video0:/dev/video0


  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - ivr_network

  rsl_api:
    container_name: rsl-api
    build:
      context: RSL-Recognition-API/
      dockerfile: Dockerfile_rsl_api
    ports:
      - "5000:5000"
    restart: always
    networks:
      - ivr_network


networks:
  ivr_network:
    driver: bridge

volumes:
  postgres_data:
